name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PHP_VERSION: '8.2'  # set this to the php version to use
  HOST: HOSTNAME    # ssh hostname
  USERNAME: USERNAME    # ssh user credentials
  KEY: KEY    # ssh key
  PATH: PATH      # ssh target directory

permissions:
  contents: read

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: ${{ env.PHP_VERSION }}
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: ${{ env.PHP_VERSION }}
    - name: Checkout origin
      uses: actions/checkout@v3
      
    - name: Setup Composer Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-vendor
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: vendor
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

    - name: Install Dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist  --optimize-autoloader --no-dev

    - name: cache laravel
      run: |
        php artisan route:cache
        php artisan config:cache
    - name: Copy file via SSH
      uses: appleboy/scp-action@master
      with:
        HOST:     ${{ env.HOST }}
        USERNAME: ${{ env.USERNAME }}
        KEY: ${{ env.KEY }}
        source: "."
        target: ${{ env.PATH }}
        strip_components: 2 # this is important
